---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 10m
  path: "./kubernetes/home/apps/flux-system/tf-controller/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tf-controller-terraforms
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 10m
  path: "./kubernetes/home/apps/flux-system/tf-controller/terraform"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  dependsOn:
    - name: tf-controller
    - name: connect
