---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: renovate
  namespace: develop
spec:
  dependsOn:
    - name: connect
      namespace: 1password
    - name: kube-prometheus-stack
      namespace: monitoring
  chart:
    spec:
      chart: renovate
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system
      version: 37.107.0
  values:
    env:
      RENOVATE_AUTODISCOVER: "true"
      RENOVATE_ALLOW_POST_UPGRADE_COMMAND_TEMPLATING: "true"
      RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: "[\"^.*\",]"
    existingSecret: renovate-secrets
    cronjob:
       schedule: "@hourly"
    renovate:
      config: '{}'
    dind:
      enabled: true
  interval: 1m0s
