---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 45.9.1
  values:
    global:
      rbac:
        createAggregateClusterRoles: true
        pspEnabled: true
        pspAnnotations:
          seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  interval: 1m0s
