---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: connect
  namespace: 1password
spec:
  chart:
    spec:
      chart: connect
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
      version: 1.14.0
  values:
    operator:
      create: true
  interval: 1m0s
