---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis-controller
  namespace: flux-system
spec:
  targetNamespace: database
  interval: 10m
  path: "./kubernetes/home/apps/database/redis-controller/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
