creation_rules:
  - path_regex: \.sops\.yaml$
    age: age12lruudqcn688pr9njrldp6haehncnuw7e2fdk84j3csqder0auhqqdcgkm
  - path_regex: .*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age12lruudqcn688pr9njrldp6haehncnuw7e2fdk84j3csqder0auhqqdcgkm
