---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-jiva-app
  namespace: flux-system
spec:
  targetNamespace: storage
  interval: 10m
  path: "./kubernetes/home/apps/storage/openebs-jiva/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-jiva-config
  namespace: flux-system
spec:
  targetNamespace: storage
  interval: 10m
  path: "./kubernetes/home/apps/storage/openebs-jiva/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: openebs-jiva-app
