---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: agones
  namespace: game
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  chart:
    spec:
      chart: agones
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: agones
        namespace: flux-system
      version: 1.36.0
  values:
    gameservers:
      namespaces:
        - game
    agones:
      createPriorityClass: false
      controller:
        replicas: 1
      ping:
        replicas: 1
      allocator:
        replicas: 1
        install: true
        service:
          serviceType: ClusterIP
  interval: 1m0s
