---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: changedetection
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: openebs-jiva
      namespace: storage
  values:
    defaultPodOptions:
      nodeSelector:
        openebs.io/data-plane: "true"
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
        containers:
          main:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: 0.45.8.1
            env:
              TZ: Europe/Amsterdam
              HIDE_REFERER: "true"
              WEBDRIVER_URL: http://selenium-router:4444
              PORT: 5000
              PUID: 568
              PGID: 568
              BASE_URL: https://changedetection.damoun.dev
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      main:
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 5000
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: openebs-jiva-csi-default
        advancedMounts:
          main:
            main:
              - path: /datastore
