---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-tf-nas
  namespace: develop
spec:
  replicas: 1
  template:
    spec:
      repository: damoun/tf-nas
      labels: ["home"]
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-tf-talos
  namespace: develop
spec:
  replicas: 1
  template:
    spec:
      repository: damoun/tf-talos
      labels: ["home"]
