apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovate
  namespace: develop
spec:
  values:
    env:
      RENOVATE_AUTODISCOVER: "true"
      LOG_LEVEL: "debug"
    existingSecret: renovate-secrets
