apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovate
  namespace: develop
spec:
  values:
    env:
      RENOVATE_AUTODISCOVER: "true"
      RENOVATE_ALLOW_POST_UPGRADE_COMMAND_TEMPLATING: "true"
      RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: "[\"^.*\",]"
    existingSecret: renovate-secrets
