apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovate
  namespace: develop
spec:
  values:
    pod:
      annotations:
        operator.1password.io/item-path: "vaults/Kubernetes/items/renovate"
        operator.1password.io/item-name: "renovate-secrets"
    env:
      RENOVATE_AUTODISCOVER: "true"
      LOG_LEVEL: "debug"
    renovate:
      secretName: renovate-secrets
