---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: develop
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: kube-prometheus-stack
      namespace: monitoring
  chart:
    spec:
      chart: actions-runner-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      version: 0.23.5
  values:
    podAnnotations:
      operator.1password.io/item-path: "vaults/Kubernetes/items/github-actions-runner"
      operator.1password.io/item-name: "github-actions-runner"
    authSecret:
      create: true
    metrics:
      serviceMonitor:
        enable: true
      serviceMonitorLabels:
        release: kube-prometheus-stack
    actionsMetrics:
      serviceMonitor: true
      serviceMonitorLabels:
        release: kube-prometheus-stack
    env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: github-actions-runner
            key: token
  interval: 1m0s
