---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  interval: 30m
  chart:
    spec:
      chart: tf-controller
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
      interval: 30m
  values:
    installCRDs: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
