---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-cert-manager.yaml
  - helm-cilium.yaml
  - helm-tofu-controller.yaml
  - helm-netbird.yaml
  - helm-descheduler.yaml
  - helm-hcloud.yaml
