---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: network
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  chart:
    spec:
      chart: cloudflared
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: damoun
        namespace: flux-system
      version: 2.0.0
  values:
    replicaCount: 2
    serviceMonitor:
      enabled: true
      extraLabels:
        release: kube-prometheus-stack
    annotations:
      operator.1password.io/item-path: "vaults/Kubernetes/items/cloudflared-credentials"
      operator.1password.io/item-name: "tunnel-credentials"
    envFrom:
      - name: CLOUDFLARED_TOKEN
        secretRef:
          name: tunnel-credentials
          key: token
  interval: 1m0s
