---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: network
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  chart:
    spec:
      chart: cloudflared
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: damoun
        namespace: flux-system
      version: 3.2.0
  values:
    replicaCount: 2
    podMonitor:
      enabled: true
    annotations:
      operator.1password.io/item-path: "vaults/Kubernetes/items/cloudflared-credentials"
      operator.1password.io/item-name: "tunnel-credentials"
    envFrom:
      - secretRef:
          name: tunnel-credentials
  interval: 1m0s
