---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: clusterplex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        openebs.io/data-plane: "true"
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542
        containers:
          main:
            nameOverride: "orchestrator"
            image:
              repository: ghcr.io/pabloromeo/clusterplex_orchestrator
              tag: 1.4.9@sha256:425bd20fae63a1a09b3974a26d71da3a6a27ba84e76986958edafc496a768237
            env:
              TZ: Europe/Amsterdam
              PGID: '65542'
              PUID: '568'
              LISTENING_PORT: "3500"
              WORKER_SELECTION_STRATEGY: "LOAD_RANK"
            resources:
              requests:
                cpu: 200m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 128Mi
      pms:
        pod:
          annotations:
            operator.1password.io/item-path: "vaults/Kubernetes/items/plex-secret"
            operator.1password.io/item-name: "plex-secret"
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542
        containers:
          main:
            image:
              repository: ghcr.io/pabloromeo/clusterplex_pms
              tag: 1.4.9@sha256:1de1ca52b239a49e898b68e9fec6f2d44293c0b42476ac446d3109ee178de40b
            env:
              TZ: Europe/Amsterdam
              PGID: '65542'
              PUID: '568'
              VERSION: docker
              DOCKER_MODS: 'ghcr.io/pabloromeo/clusterplex_dockermod:1.4.8'
              ORCHESTRATOR_URL: 'http://{{ .Release.Name }}:3500'
              PMS_SERVICE: '{{ .Release.Name }}-pms'
              PMS_PORT: '32400'
              TRANSCODER_VERBOSE: '1'
              TRANSCODE_OPERATING_MODE: 'both'
              LOCAL_RELAY_ENABLED: '1'
              LOCAL_RELAY_PORT: '32499'
            envFrom:
              - secretRef:
                  name: plex-secret
            resources:
              requests:
                cpu: 2000m
                memory: 2Gi
              limits:
                cpu: 4000m
                memory: 4Gi
      worker:
        type: statefulset
        replicas: 2
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542
        containers:
          main:
            image:
              repository: ghcr.io/pabloromeo/clusterplex_worker
              tag: 1.4.9@sha256:9f59f97f5b7e2dd5e4ce18bbb75b262b260a7e2669e78e3d3567bf20d5c88177
            env:
              TZ: Europe/Amsterdam
              PGID: '65542'
              PUID: '568'
              VERSION: docker
              DOCKER_MODS: 'ghcr.io/pabloromeo/clusterplex_worker_dockermod:1.4.8'
              ORCHESTRATOR_URL: 'http://{{ .Release.Name }}:3500'
              LISTENING_PORT: '3501'
              STAT_CPU_INTERVAL: '10000'
              EAE_SUPPORT: '1'
            resources:
              requests:
                cpu: 2000m
                memory: 3Gi
              limits:
                cpu: 4000m
                memory: 6Gi
    service:
      main:
        ports:
          http:
            port: 3500
      pms:
        controller: pms
        ports:
          http:
            port: 32400
          relay:
            port: 32499
      remote:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        controller: pms
        ports:
          http:
            port: 32400
      worker:
        controller: worker
        ports:
          http:
            port: 3501
    ingress:
      pms:
        enabled: true
        className: "nginx"
        hosts:
          - host: "plex.home.damoun.cloud"
            paths:
              - path: /
                service:
                  name: pms
                  port: http
    persistence:
      config-pms:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-jiva-csi-default
        size: 25Gi
        advancedMounts:
          pms:
            main:
              - path: /config
      transcode:
        enabled: true
        type: nfs
        server: nas.home.damoun.cloud
        path: /mnt/pool1/kubernetes/transcoding
        advancedMounts:
          worker:
            main:
              - path: /transcode
          pms:
            main:
              - path: /transcode
      media:
        enabled: true
        type: nfs
        server: nas.home.damoun.cloud
        path: /mnt/pool1/video
        advancedMounts:
          worker:
            main:
              - path: /media
          pms:
            main:
              - path: /media
