---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: clusterplex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: clusterplex
      version: 1.1.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: clusterplex
        namespace: flux-system
  values:
    global:
      nodeSelector:
        openebs.io/data-plane: "true"
      timezone: Europe/Amsterdam
      PGID: 65542
      PUID: 568
      sharedStorage:
        transcode:
          enabled: true
          type: nfs
          server: nas.home.damoun.cloud
          path: /mnt/pool1/kubernetes/transcoding
        media:
          enabled: true
          type: nfs
          server: nas.home.damoun.cloud
          path: /mnt/pool1/video
    pms:
      config:
        ingressConfig:
          enabled: true
          ingressClassName: "nginx"
          hosts:
            - host: plex.home.damoun.cloud
              paths:
                - path: /
                  pathType: Prefix
      configVolume:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-jiva-csi-default
        size: 5Gi
    worker:
      codecVolumes:
        enabled: true
        storageClass: openebs-jiva-csi-default