---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/1password.yaml
  - ../base/actions-runner-controller.yaml
  - ../base/damoun.yaml
  - ../base/jetstack.yaml
  - ../base/prometheus-community.yaml
  - ../base/renovate.yaml
  - ../base/zalando-postgres-operator.yaml
  - ../base/openebs-jiva.yaml
  - ../base/mongodb.yaml
