---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: selenium-grid
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: selenium-grid
      version: 0.26.2
      sourceRef:
        kind: HelmRepository
        name: selenium
        namespace: flux-system
  values:
    isolateComponents: true
    autoscaling:
      enabled: true
    basicAuth:
      enabled: false
    ingress:
      enabled: false
