---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-jiva
  namespace: openebs-jiva
spec:
  chart:
    spec:
      chart: jiva
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs-jiva
      version: 3.5.1
  values: 
  interval: 1m0s
