---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 30m
  dependsOn:
    - name: openebs-jiva
      namespace: storage
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        openebs.io/data-plane: "true"
    controllers:
      main:
        pod:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          annotations:
            operator.1password.io/item-path: "vaults/Kubernetes/items/home-assistant"
            operator.1password.io/item-name: "home-assistant"
        initContainers:
          git:
            image:
              repository: bitnami/git
              tag: 2.43.0@sha256:12396596a8c8b8477ce66d04ee6bc0caebd992f217a4711e0c7546fd64c39ce3
            command:
              - "/bin/sh"
              - "-c"
            args:
              - "git clone https://github.com/damoun/hass-config.git /config || (cd /config ; git fetch --all && git reset --hard origin/main)"
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2023.12.4@sha256:8d000332b09b71fd946f596b1f721b0af969263b6f27ebc1d212fdbd13bb1bd8
            env:
              SECRET_EXTERNAL_URL: http://hass.home.damoun.cloud
              SECRET_INTERNAL_URL: http://home-assistant:8123
              SECRET_TRUSTED_PROXIES_1: 10.244.0.0/16
              SECRET_RECORDER_DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: "postgresql-app"
                    key: uri
            envFrom:
              - secretRef:
                  name: "home-assistant"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 47m
                memory: 1254M
              limits:
                memory: 1254M

    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 8123
          homekit:
            port: 21063

    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: "hass.home.damoun.cloud"
            paths:
              - path: /
                service:
                  name: main
                  port: http

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-jiva-csi-default
        globalMounts:
          - path: /config
