---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 30m
  dependsOn:
    - name: openebs-jiva
      namespace: storage
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        openebs.io/data-plane: "true"
    controllers:
      main:
        pod:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          annotations:
            operator.1password.io/item-path: "vaults/Kubernetes/items/home-assistant"
            operator.1password.io/item-name: "home-assistant"
        initContainers:
          git:
            image:
              repository: bitnami/git
              tag: 2.44.0@sha256:7c3741d267fe466614d1e7be2d3989d51ea4127ba7385402c5fc18d43d0ba329
            command:
              - "/bin/sh"
              - "-c"
            args:
              - "git clone https://github.com/damoun/hass-config.git /config || (cd /config ; git fetch --all && git reset --hard origin/main)"
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.3.1@sha256:9dade9391001b769a791a03faf9f193a9c801e711922f0469d27a3d923b9dfe0
            env:
              SECRET_EXTERNAL_URL: http://hass.home.damoun.cloud
              SECRET_INTERNAL_URL: http://home-assistant:8123
              SECRET_TRUSTED_PROXIES_1: 10.244.0.0/16
              SECRET_RECORDER_DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: "postgresql-app"
                    key: uri
            envFrom:
              - secretRef:
                  name: "home-assistant"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 47m
                memory: 1254M
              limits:
                memory: 1254M

    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 8123
          homekit:
            port: 21063

    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: "hass.home.damoun.cloud"
            paths:
              - path: /
                service:
                  name: main
                  port: http

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-jiva-csi-default
        globalMounts:
          - path: /config
