---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 30m
  dependsOn:
    - name: openebs-jiva
      namespace: storage
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        openebs.io/data-plane: "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2023.12.1@sha256:93b9ebc8a464475f42113ccf121bb3c495ce2b4adc0a6fe2c7c3946a5912e850
            env:
              SECRET_EXTERNAL_URL: http://hass.home.damoun.cloud
              SECRET_TRUSTED_PROXIES_1: 10.244.0.0/16
              SECRET_RECORDER_DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: "postgresql-app"
                    key: uri
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 47m
                memory: 1254M
              limits:
                memory: 1254M

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: "hass.home.damoun.cloud"
            paths:
              - path: /
                service:
                  name: main
                  port: http

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-jiva-csi-default
        advancedMounts:
          main:
            main:
              - path: /config
