apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: autobrr-postgresql
  namespace: download
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  affinity:
    nodeSelector:
      openebs.io/engine: mayastor
  storage:
    storageClass: openebs-mayastor-dual-replica
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  resources:
    limits:
      hugepages-2Mi: 512Mi
      memory: 512Mi
