apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: monitoring
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  affinity:
    nodeSelector:
      openebs.io/engine: mayastor
  storage:
    storageClass: openebs-mayastor-dual-replica
    size: 10Gi
  monitoring:
    enablePodMonitor: true
