---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/1password-connect
  - ../base/actions-runner-controller
  - ../base/postgres-operator
  - ../base/openebs-jiva/
resources:
  - ../base/prometheus-operator.yaml
  - ../base/mongo-operator.yaml
