---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/1password-connect
  - ../base/prometheus-operator.yaml
  - ../base/actions-runner-controller
  - ../base/postgres-operator
