---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/1password-connect
  - ../base/actions-runner-controller
  - ../base/openebs-jiva
  - ../base/cloudnative-pg
resources:
  - ../base/prometheus-operator.yaml
  - ../base/mongo-operator.yaml
