---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: connect
  namespace: flux-system
spec:
  targetNamespace: 1password
  interval: 10m
  path: "./kubernetes/home/apps/1password/connect/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
