---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbtools-prune
  namespace: download
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: qbittorrent

  values:
    controllers:
      main:
        type: cronjob

        cronjob:
          schedule: "5 * * * *"

        pod:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 568
            runAsGroup: 568

        containers:
          main:
            image:
              repository: ghcr.io/buroa/qbtools
              tag: v0.11.0
            args:
              - prune
              - --exclude-category
              - manual
              - --include-tag
              - unregistered
              - --dry-run
              - --server
              - qbittorrent
              - --port
              - "8080"
            resources:
              requests:
                memory: 64Mi
                cpu: 5m
              limits:
                memory: 128Mi

    service:
      main:
        enabled: false