apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    defaultRules:
      create: false
    alertmanager:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      agentMode: true
      annotations:
        operator.1password.io/item-path: "vaults/Kubernetes/items/mimir-remote-write"
        operator.1password.io/item-name: "mimir-remote-write"
      prometheusSpec:
        remoteWrite:
          - url: https://mimir.damoun.cloud/api/v1/receive
            basicAuth:
              username:
                name: mimir-remote-write
                key: username
              password:
                name: mimir-remote-write
                key: password
