apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    defaultRules:
      create: false
    grafana:
      enabled: false
      defaultDashboardsEnabled: false
      annotations:
        operator.1password.io/item-path: "vaults/Kubernetes/items/grafana-secrets"
        operator.1password.io/item-name: "grafana-secrets"
      admin:
        existingSecret: "grafana-secrets"
        userKey: username
        passwordKey: password
      env:
        GF_DATABASE_TYPE: postgres
        GF_DATABASE_SSL_MODE: disable
      envValueFrom:
        GF_DATABASE_USER:
          secretKeyRef:
            name: grafana-secrets
            key: dbUser
        GF_DATABASE_PASSWORD:
          secretKeyRef:
            name: grafana-secrets
            key: dbPassword
        GF_DATABASE_HOST:
          secretKeyRef:
            name: grafana-secrets
            key: dbHost
        GF_DATABASE_NAME:
          secretKeyRef:
            name: grafana-secrets
            key: dbName
    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: node-exporter
            scheme: http
            static_configs:
              - targets:
                - pve.home.damoun.cloud:9100
                - vpn1.home.damoun.cloud:9100
                - nas.home.damoun.cloud:9100
