---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/monitoring
  - ../../base/monitoring/kube-prometheus-stack
  - ../../base/monitoring/speedtest-exporter
patchesStrategicMerge:
  - namespace.yaml
  - values.yaml
