---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: autobrr
  namespace: flux-system
spec:
  targetNamespace: download
  interval: 10m
  path: "./kubernetes/home/apps/download/autobrr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: cloudnative-pg
