---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
bases:
  - ../../base/network/omada-controller/
  - https://github.com/mongodb/mongodb-kubernetes-operator//config/rbac/?ref=v0.7.9&submodules=false
resources:
  - ./mongo.yaml
  - ./secrets.yaml
patches:
  - path: omada-controller.yaml
