---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/network/omada-controller/
resources:
  - ./mongo.yaml
  - ./secrets.yaml
  - https://github.com/mongodb/helm-charts/raw/community-operator-0.7.9/charts/community-operator/templates/database_roles.yaml
