---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo-omada-controller
  namespace: network
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  statefulSet:
    spec:
      template:
        spec:
          initContainers:
            - command:
              - chown
              - -R
              - "2000"
              - /data
              image: busybox@sha256:6e494387c901caf429c1bf77bd92fb82b33a68c0e19f6d1aa6a3ac8d27a7049d
              volumeMounts:
                - mountPath: /data
                  name: data-volume
              securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0
              name: change-dir-permissions
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: openebs-jiva-csi-default
            resources:
              requests:
                storage: 8Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: openebs-jiva-csi-default
            resources:
              requests:
                storage: 2Gi
  users:
    - name: omada
      db: admin
      passwordSecretRef:
        name: mongo-omada-admin-credentials
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: omada
      connectionStringSecretName: mongo-omada-connection-string
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
