---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada-controller
  namespace: network
spec:
  values:
    mongoUri:
      secretName: mongo-omada-connection-string
      secretKey: connectionString.standard
    service:
      tcp:
        type: NodePort
        ports:
          adoptV1: 32001
          upgradeV1: 32002
          managerV1: 32003
          managerV2: 32004
        nodePorts:
          adoptV1: 32001
          upgradeV1: 32002
          managerV1: 32003
          managerV2: 32004
      udp:
        type: NodePort
        ports:
          discovery: 32000
        nodePorts:
          discovery: 32000
    containerPorts:
      discovery: 32000
      adoptV1: 32001
      upgradeV1: 32002
      managerV1: 32003
      managerV2: 32004
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    image: ghcr.io/damoun/omada-controller:main
    imagePullPolicy: Always
