---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada-controller
  namespace: network
spec:
  values:
    mongoUri:
      secretName: mongo-omada-connection-string
      secretKey: connectionString.standard
