---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada-controller
  namespace: network
spec:
  values:
    mongoUri:
      secretName: mongo-omada-connection-string
      secretKey: connectionString.standard
    service:
      type: NodePort
      ports:
        discovery: 32000
      nodePorts:
        discovery: 32000
    containerPorts:
      discovery: 32000
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    image: ghcr.io/damoun/omada-controller:main
