apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-pg
  namespace: cnpg-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
      namespace: monitoring
  values:
    monitoring:
      podMonitorEnabled: true
