---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 1password
resources:
  - namespace.yaml
  - secret-op-credentials.yaml
  - secret-onepassword-token.yaml
  - helmrepo.yaml
  - helmrelease.yaml
