apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
    namespace: 1password
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:NE7e0Te+4l4xI5mei4kWDdMc+BBDLc4/PTwkk5t7UVZvo6NPdhtvpAfU+CQs5w9OhM3ILKSZI8NuLlFiAHrECrpfZxEsqcaXAzh3VvGHC0Ksdgg2aZQqU175B+dbVDW+GkgW7ArCKJXTIbT3W88EflXEz8a3r+Sa23Ag/ZoZ9NOyaeQIPHvByCaB79+rejiQ/6p6EnD/KYsHkzmfiHWXwIySDYpH7vz4PX8j4qjYCEGVPpNS87qIeAon9IDPHaOOJsWvXKGc53XLms1e15K5S0qn3Bg4P9/b7wd1PAN7Ekt2eXai7LHReRbH0d4mBEzhW64mvDCFsM3wuROORfxK9zRKZMhtKB0r3cf1DvfiZcGWDHMggu1HdC8jOBF+1TKHJBVIj88IHEYin8BjtFNvGT+G85nbHocrmsz6/VkzmvUpn2lK548ORU/dAS3wDI0WDwLYx3u0PD4a1lqDSEZW6AtjcaRR6CtW64Z/WQNev7kyN6EcOBk/1nDgI7zbJb652KbeTVUvJl4mSGIzruUgypfitt30+4JJNKCRHaYqwEoaZh5DdaeDOdgBo9mycjQeNNBKnDnBTmpihsKtFL+PbMJC3VVshtkbIdME8nB5995gLlfT/WTRdNSPcdtLtIsbXRa38yDH6vTOZuyKRP4TDTCaHhAK0S3Oz9HbxbLWgOAUUSw8o8C4t88tl46fx6Ngw0r88GZOOQcnbuL9seKU6y8toJOmXdQWecZ4xJ6oSy7FssHCiM5W5WmuDixH0LNWOhjxoDrGo0GIe/MSoc7nPYB3Q9Y6LqTG7uGtIhd0eer5ob7hQoBQqhyJ33xa/hd9R6ykMvKFh3OvigKEA73rR9VhDsBWJeyqt9aTZ+6oZrw1Hsci9n8R2j0krAhMTWWC8oNSHKb7vs2c81mmHcfOW2di6aEB4F5djTUGhrXIFMQLXA/QMzQcOCmdi5XoVm06KLK15thAYAdvh6DKQf0mGjpzohBJLxW+NZnf0Fdc5L2euKl53kSCEj0/FRuCm9PI/Iwal4jL0iwyP959dmfKDAHsXT0U6Zkhwz1LXCmbvuu2weW1j/coDefKiiComLn0ewwZodLw6ratAVr9yCbxCudXspK5nJig99lB7Kd7qFAhZMdZJKXqGG7ZLNtlYXz5gfd2HSkxJ3VZ17VIW0GsMTOFm7dDFa7x9b6Bcg68qX9/TwTubMRiQ5X6I01vYmJAleaX3YrPGJpp5I8xmBqs6E/+VgkvunxkkuytUhuKjt98zJsV8t/dz11irJjM0RGITMUqdsxj0ehU0PA114ntaJFMgolwh0uessRBg9Df1xGV3dVNbTjK8KHA9id6VpyWiJ6hP2N9rYQLFlsk7xoSSsR1Y79l7mLVUZ7h5d02mQslviqLfqae4zykgnTgUXBsukHh6o8hNIbvjS91DpYA58BtpKUkUJoSsbWFz3w2NvHZhtuzrZdNJah2puVgjfuek6bphddrP05fABwuCYr7P1U50h+4HjbVoxVCfudY1hw1qwu5wDW9gNQk1KNRM7fzZYYZvRGihdcBs/Ng6/ggKwEFX+mGGluENJYGocXpg+Iutoy9bxdy47UTyNXg4LL/QymepGSc1sna2BlYGnMt2Ufodv6cTXXe4WXfoPlyM6cPHSYBRReqe95zqk05/iVpWO6tZdi8WQ5hhryRs6SjDe3gffxvnpSkrdMPTz9D+7o2Ow9yANxAbIscInddWpvbrYi+8HCk2byU2GhLEd/mX3oU7VoSGnUqqjT7EB9tGyE+1AZ/2/L7QcVXuG63RCJRxEvaZKpixRbHvzFO/EsPY0NG+9Xynd09OvyC/7fxtBzHoddBBFrpo5kz9olN8j2u0703SA4sGOjI4g/1AgeSoo4z+T4gDlr7MUFSX4Ug+FUf8I+v9q4+fb/tplw=,iv:8XyyD+J03WTQpMxfHb2HoF3xH+reBjTwujaXu/j3nXk=,tag:znSunPOtE0rQUskT9YCcwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-01T20:27:58Z"
    mac: ENC[AES256_GCM,data:7+YWqtGz+b8es/AphI51t0o47cZzZSl27XcRrWeeeRM4yCx3nGYHLcIvqPfAmlMHz7kE5fHXQwCeUxBRQyq7iidwHDDLZJV+0joazPIRYntiDFATXVi6oeQJm3umriSWynMto7yJ22Z+1bqhYhyJZocSuLpCpTspR/3IPMu78bc=,iv:Kp7EuJ6bKDwtLzBPZGmotSIDeefoVcBRjOBcuMRyWHE=,tag:JzN9Oyz0CKiR2oQ0H/s1lg==,type:str]
    pgp:
        - created_at: "2023-04-01T20:27:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxfu3g8LdXaRARAAiW58SdDG3ByO7FEO0ZGM9mCKPuffo0NOJRidLqISyW0g
            nQNsmd+eTyqtFfX49Tsim/Rcxuj77pjwchzRA+P+Yu7BS81NcjB6vXfVL+R6Rs3H
            M7zyPf/NLzQ8swaOw1g9egbpxttHRa+XaiGUqI9eHasPR7DyVFtCvgj5hLTtWrjH
            3Rs3XXUM2HM66PmAoSDI1Sn/+8UsmzfwnlWtMe8dfrfU4XlDIV+v13+mqoB5VL2X
            eLvIH7Bwj18zJW5g2UM42zlDf1X3gLPX+Vc7EbH4YbzaodRaFRDFW7VeBe5N+ozY
            2zPoRXT5n80VVoTjATS0aPqVio8Zf7fEJiXDsrj3cL23TG/RoASRcegqIxSFq5QK
            2zRPQ8bt8ltD0oLA4O8K4s5qbs44RmDg8xFvPCoGKi501ZuV9fnbOWWVMVUDxFrg
            MZxB9Z4CvNhg2YnDlByW8/51Tvrep2A1oUbcoueUqHbaYDlHsmQaGHsaAp+uYhf6
            TtWRzZZRGAMAZ50033VDnPD4ibg4gICTmabbSGvee3LOM0h2YDuoMofXjEACeVjT
            2G3zpCnrFxWt15OahGHqLnsvFxh1XJoIHH4cxpi/ZYCRbytR4yV0Z5eerwNHsZCk
            W58cpxf0h7dRi9OVinveLnfkdehjg52KdweeJURaVXXTXGYfwvfwufAuGM+hSizS
            XgHTcAas7JcoHiJ9HPTlvpVYCNEJF+TZxbMFwzRlK5LIUz0Bf+19rEP0Jyaay9eS
            vrEcvBC2cxMBpCUDoFDuBryaX5B3fXr/ZEaOXgSPJqX/x896sTpzajRkktqlJwI=
            =3eci
            -----END PGP MESSAGE-----
          fp: 8BC21F9620077AD4B9BD97EF5C350D68F61028B3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
