apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
    namespace: 1password
data:
    op-session: ENC[AES256_GCM,data:Qxi6O9Xl9/AznAPtplOw4tsO72psss3yQIep6Vn5rTPVdE5nKhswM1M/j1Y1+AEAZRaiIdkDLcd0BZIgN+15WagUeSbEJ/j8/RKsY+zA9slw93m/acARtyT9qUsHR7ZTCIYp2jtpKINT+k2kEewZYQgmyDAXFhlrrusBIYPP+3tOWqI4kZirPXAajLLXQVlMn5YUqxzmezMS85xy2TRopzahDmLHvJWdVdnjCOd1uAGWDo4WlUEEtdaS00KIsFneIXzgTFMzv7szCKahLwfPTraYy3oZY78lziZ3siBeetO/1IFUMAo5MCQsWXgD2OluyutXFGMuErgIZUGKoH/Z96HkjTbLvc1uAZgW/GD5gaMpW+9Jd5PfUnSrkRuWYi51cyb5AtaxpMgegl6uzhu/gj+/I6ZgnGUTssSz2QhRcvVndP5RgtpHLHZdpUbiHrE1db6TL0HhzBTKtBJWuq/gb7j90Vg7BcRwRp8z+XhPzvV4D1tLgkGcPRC59WtTe8tiZ9MFov1TOvspU7psUD7jE+ldffYyZ6iNZrc5SlhT4i7LC6fFM07QcseaPECHukrFTcPXGuGq8YJfVeedNFFsa3NE+cb7eldwrs0h/H0Mh9mjdon/3dzwvVpw7uZ6frTnu1qLYyL73/DOpY7X6LB5TG4qosFr9h+bAPf0GCIJXDi/ZzBbuwsMnmYKBzlFKu6M+vNrJ+WGoSpl+CNowONSLT+IRZgR8EZ2RNdwKZGCVIFvN6xwF+yFKzzEyFSocqxUyNvHfxZV/wRNtOb1rpsoPWaLeuRzZ4Ix/1dow7Hf2NoyJdalQc61o4C3GEpQaAoQXRisLy+XvUaQlcCVtE9QUsosIVfnoKTxk/Ts76uDADoWUFEGa3uTwj4UZORXHOJy5KyLTHhTikzHW4y/+2U3aM+SN39KdSO+fT7OB28jUcpjN2aLaPuyJqlpYYDcK8SsnvZ911v6SmZOlZor0dW7QKmOSu22kb+71gdSYEdidRr+3BNhTg6cxUondup0F7j9TIGNS0a8lHQCx6sNnRpWT2u3nhWmy2C8KlqeWTqj2WfacK2K+bj5HeTypicFYE5KDLECY8sSOoTT/8YW7X5HB4dP/tKadpnEbpZ5/F4GML5Amx2iQ4bznMFOLwaZ9vLRG8CcTWcl2POYIbmx0IUsx4y9r9NetHUh+m8KS4XzZAdQ79Qri3GYOnzOFGiy6EDnYniQcTfdwFJ2UDI3omjei+zTqWxu6f8QkRAqyJxdFzVcBMR0UJd0ENbarQskITF7yHQlUGc/NMMWQUsG60ILfa5Ks89yj43oSVSqbAr7n/K+aDmK0rTpCzfntrPts2brRpiSsQmj/dptSVCFMSn6+KgRuBODHSt1ueQHbqhdYtxIgaLuTDM45FN4BqPFGcEpxN9apAG32RnTjG4sjlwV1fB4ZaQZkL7gPo6d9WEAk3640GnK4bHtDcWdpHHuoiIiysJqGSo+i9ZSO1WAfgEqhxNCdL/XmUVCqF4YlqQOoC2vOHhBeXYOecwjV+cggm2mGBmWvPzBJDdI3urtMGmNfe5KAMDbLOllQYDKfPOezzdnOyUHHo3cTJkcVJEhGoLgb3tTemEh12ICWIEaZ80Rmr04jSxSjHITfxFUhOb9U3QQ9VxqUV5SLEXlRIc/BnUj3XuikinMYX2oy2HvEgtgIcF8XWKxGVPjiOoVI6Brj0Zgrs6/QTa+zyS34RIzv/Ss81qJGUYKFvvOiQH1PAjUAqXF3lIDt76fG30SuM6Kg6DpPzv/zdiLIp5Jt09l2pbMSn4EBOrmRQuRN2raeCEae9eQvkSohVEBEEc8yj+vGF0rsWrN0wcm0SMjhHddU90HhuJwTyRn38bAp9DWFz0ts23fcuRQZP1IOQTScYrSV2ZJD6BdsMS/IpLFnbE=,iv:38Lv++CUvK9dlvD4nKZwyOtQyaXfP/yNU1UM65e9n2Y=,tag:TkBgY0orw0tgP+4hpY861w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-01T20:02:39Z"
    mac: ENC[AES256_GCM,data:E52/4R+KJrr49p9jxSmfixfidaD2ANO1CM91S94weXkXbYCIC1pg6Mh8N17PVA2eoCK1BzTCrwXMoAyx7R2KYkByWKEDZS0VFhRTOjU9dp/d3UrzTURsBaQ5Mf0csdCpOSnOmNJvw8pXz3d8G9h4IbiZ1pBrYvQTMxS3jvvIFYQ=,iv:AQTxPF5rFyO+zONmyEIlTo1+TO8cyAy+9zbWptNtJNQ=,tag:pd9D3TZa7FKPHIpX36aWOw==,type:str]
    pgp:
        - created_at: "2023-04-01T20:02:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxfu3g8LdXaRAQ//dNdns0E6a6dYNR/FZ1AR/7TpJf1Y4MtePQRyJhRkPhIw
            sPSjO1DRtVbvCTKM3H2yqU9Ofu8ejENDXngKiJPHLI6IQW3WfRDcvI4kIWeeSuMM
            GMlCIs/Ek6GcACbdH9XXpXXw/KgaVVKw6BBPDxtqz9r5hgbEC6F9ZN+rxl2YvKq/
            RPbPVkB/cMYHgiSxQMovr3G70hJj/KnHc5XUqbZESObrNOfWAUZVFImJ2RF1adPx
            58i2kbSwS0dhbvxhXzxpO1Gj05Ow2Hw4yikfhWdnb/zcXUaWDZ3cPDUtvUH/pm8X
            Daxa1F0Bhx+19R9+k7IqnGw3bdKvuK4PwGlSpSgNRurHQ3OJEuxfTG3fFAxJH2zO
            HOQk1QB4T3sHHecE0jZ7jhVHWHd9wIIgENSgqELfwYWktIfgB4uemumA7lWUsrCM
            VAOtjzMWa4eQJsP1Z3w5uuXxNs6uJitJHDWJG1ObX+SO9M+fHDmiZxjFKe8BUp5P
            SP19adcnpDAh87/8mAEROt6KPCFBCnrJFYq7LqAoDNFlivhfmBRamYr92KVr1k15
            rKKxWOzkt2Z16y7BqPVW+CQHAlxgI/EkYAG8nD/5jgYGaKlZZ0FExo5tmaJlJa4A
            e+VXLTxjmGkr2qVyM5mBcjtKyFDSpHJvt2Un/uTN5HNqMHdzbWSdljjP3+rvoJDS
            XgHQsPZ3C6xVX6fSSJzoz+pnA6f8LRuFm65QN9vZXwFGssfQUDJ0ZOiPcWBf61Og
            vi6tqvX2sXKNcCP3Io8UWlNYjOGWc/yNhpahICLCjU+FYa2j4i1uHNJski1FJsA=
            =O5BI
            -----END PGP MESSAGE-----
          fp: 8BC21F9620077AD4B9BD97EF5C350D68F61028B3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
