---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - ../../base/develop/renovate
  - ../../base/develop/actions-runner-controller
  - actions-runners.yaml
patchesStrategicMerge:
  - renovate.yaml
  - actions-runner-controller.yaml
