---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 1m0s
  url: https://raw.githubusercontent.com/1Password/connect-helm-charts/gh-pages/
