---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: develop
spec:
  interval: 1m0s
  url: https://actions.github.io/actions-runner-controller
