---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  values:
    persistence:
      enabled: true
    configmap:
      config:
        data:
          configuration.yaml: |
            default_config:
            recorder:
              db_url: !env_var uri
            http:
              use_x_forwarded_for: true
              trusted_proxies:
                - "10.0.0.0/8"
    envFrom:
      - secretRef:
          name: postgresql-app
