---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: code-server
  namespace: develop
spec:
  chart:
    spec:
      chart: ./ci/helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: coder-code-server
        namespace: flux-system
      version: 3.15.1
  values:
    podAnnotations:
      operator.1password.io/item-path: "vaults/Kubernetes/items/code-server"
      operator.1password.io/item-name: "code-server"
    existingSecret: "code-server"
    persistence:
      enabled: false
  interval: 1m0s
