---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: radarr
  namespace: download
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        openebs.io/data-plane: "true"
    controllers:
      main:
        pod:
          annotations:
            operator.1password.io/item-path: "vaults/Kubernetes/items/radarr-secret"
            operator.1password.io/item-name: "radarr-secret"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/radarr-develop
              tag: 5.2.4.8328@sha256:9908d5e7ef16122cfdf80fa0d1fefef743cc598346bc12c3408e645d99012c74
            env:
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: 7878
              RADARR__AUTHENTICATION_METHOD: External
              RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              RADARR__APPLICATION_URL: "http://radarr.home.damoun.cloud"
              RADARR__LOG_LEVEL: info
              RADARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: api_key
            resources:
              requests:
                cpu: 14m
                memory: 431M
              limits:
                memory: 431M
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: "radarr.home.damoun.cloud"
            paths:
              - path: /
                service:
                  name: main
                  port: http
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-jiva-csi-default
      media:
        enabled: true
        type: nfs
        server: nas.home.damoun.cloud
        path: /mnt/pool1/download
        globalMounts:
          - path: /data/nas-media
