---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: download
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        openebs.io/data-plane: "true"
    controllers:
      main:
        pod:
          annotations:
            operator.1password.io/item-path: "vaults/Kubernetes/items/prowlarr-secret"
            operator.1password.io/item-name: "prowlarr-secret"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/prowlarr-nightly
              tag: 1.11.2.4160@sha256:936a6d3f835fba6f616b5a0440dd2821a1e44dcdd05cca53e1236c42d0198f1a
            env:
              PROWLARR__INSTANCE_NAME: Prowlarr
              PROWLARR__PORT: 9696
              PROWLARR__LOG_LEVEL: info
              PROWLARR__ANALYTICS_ENABLED: "False"
              PROWLARR__AUTHENTICATION_METHOD: External
              PROWLARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: prowlarr-secret
                    key: api_key
            resources:
              requests:
                cpu: 18m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      main:
        ports:
          http:
            port: 9696
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: "prowlarr.home.damoun.cloud"
            paths:
              - path: /
                service:
                  name: main
                  port: http
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-jiva-csi-default
