---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: download
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        openebs.io/data-plane: "true"
    controllers:
      main:
        pod:
          annotations:
            operator.1password.io/item-path: "vaults/Kubernetes/items/qbittorrent-secret"
            operator.1password.io/item-name: "qbittorrent-secret"
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542
        containers:
          main:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.3@sha256:f2895e632fe66299d8ccc68265cc11aea92a232b7d0844de9961864b3e504026
            env:
              UMASK: "022"
              QBITTORRENT__PORT: 8080
            resources:
              requests:
                cpu: 49m
                memory: 1024Mi
              limits:
                memory: 8192Mi
            securityContext:
              runAsUser: 568
              runAsGroup: 568
          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-18
              tag: 1.8.3@sha256:5f2e92f6363db2bd5bd40319ac2fb10e3a583f6ff5fb5d96a948d9c8b93299b3
            securityContext:
              runAsUser: 0
              runAsGroup: 0
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: latest@sha256:1f3a41529a6a05a1c1b5003fdd09ebbf6f6a926b01aa010002c0d5c52b0f1397
            env:
              - name: VPN_SERVICE_PROVIDER
                value: custom
              - name: VPN_TYPE
                value: wireguard
              - name: VPN_INTERFACE
                value: wg0
              - name: VPN_ENDPOINT_PORT
                value: "51820"
              - name: VPN_PORT_FORWARDING
                value: "on"
              - name: VPN_PORT_FORWARDING_PROVIDER
                value: "protonvpn"
              - name: FIREWALL_INPUT_PORTS
                value: "8080"
              - name: FIREWALL_OUTBOUND_SUBNETS
                value: "10.96.0.0/12,10.244.0.0/16"
              - name: SHADOWSOCKS
                value: "on"
              - name: DOT
                value: "off"
              - name: DNS_PLAINTEXT_ADDRESS
                value: "127.0.0.2"
              - name: SHADOWSOCKS_LOG
                value: "on"
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
          port-forward:
            image:
              repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
              tag: "1.3@sha256:679b7a92c494f93b78ad37ef24f3a261e73d0a1a52505ad4f1e39580eedfa14f"
            env:
              - name: QBITTORRENT_SERVER
                value: localhost
              - name: QBITTORRENT_PORT
                value: "8080"
              - name: PORT_FORWARDED
                value: "/tmp/gluetun/forwarded_port"
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: "torrent.home.damoun.cloud"
            paths:
              - path: /
                service:
                  name: main
                  port: http
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-jiva-csi-default
        size: 512Mi
        advancedMounts:
          main:
            main:
              - path: /config
      download:
        enabled: true
        type: nfs
        server: nas.home.damoun.cloud
        path: /mnt/pool1/download
        advancedMounts:
          main:
            main:
              - path: /data/download
      tvshow:
        enabled: true
        type: nfs
        server: nas.home.damoun.cloud
        path: /mnt/pool1/video/tv-show
        advancedMounts:
          main:
            main:
              - path: /data/tv-show
      movie:
        enabled: true
        type: nfs
        server: nas.home.damoun.cloud
        path: /mnt/pool1/video/movie
        advancedMounts:
          main:
            main:
              - path: /data/movie
      dnsdist-config:
        type: configMap
        name: qbittorrent-dnsdist
        advancedMounts:
          main:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true
      gluetun-data:
        type: emptyDir
        advancedMounts:
          main:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun
                readOnly: true
