apiVersion: openebs.io/v1alpha1
kind: JivaVolumePolicy
metadata:
  name: openebs-jiva-default-policy
  namespace: storage
spec:
  replicaSC: openebs-hostpath
  target:
    replicationFactor: 3
    nodeSelector:
      openebs.io/engine: mayastor
  replica:
    nodeSelector:
      openebs.io/engine: mayastor
