---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbtools-reannounce
  namespace: download
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: qbittorrent

  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568

        containers:
          main:
            image:
              repository: ghcr.io/buroa/qbtools
              tag: v0.11.0
            args:
              - reannounce
              - --process-seeding
              - -s
              - qbittorrent.downloads.svc.cluster.local
              - -p
              - "8080"
            resources:
              requests:
                memory: 250Mi
                cpu: 25m
              limits:
                memory: 500Mi

    service:
      main:
        enabled: false
