---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: database
spec:
  chart:
    spec:
      chart: redis-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ot-container-kit
        namespace: flux-system
      version: 0.15.9
  values:
    redisOperator:
      watch_namespace: "*"
  interval: 1m0s
