---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: database
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  chart:
    spec:
      chart: redis-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: spotahome-redis-operator
        namespace: flux-system
      version: 3.3.0
  values:
    monitoring:
      enabled: true
      serviceMonitor: true
  interval: 1m0s
