---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  chart:
    spec:
      chart: cloudflared
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: damoun
      version: 1.2.0
  values: 
  interval: 1m0s
