---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cilium.yaml
  - tofu-controller.yaml
  - namespace-netbird.yaml
  - netbird-api-token.yaml
  - netbird.yaml
  - netbird-kubernetes-resources.yaml
  - netbird-routing-peer.yaml
  - netbird-routing-peer-pdb.yaml
  - descheduler.yaml
  - hcloud-csi.yaml
