---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cilium.yaml
  - tofu-controller.yaml
  - netbird-api-token.yaml
  - netbird.yaml
  - hcloud-csi.yaml
