---
apiVersion: netbird.io/v1
kind: NBPolicy
metadata:
  name: kubernetes-policy
  namespace: netbird
spec:
  name: Admins to Kube API
  sourceGroups:
    - admins
  destinationGroups:
    - dmn-fsn-tools
  bidirectional: false
  protocols:
    - tcp
  ports:
    - 6443
