---
apiVersion: netbird.io/v1
kind: NBResource
metadata:
  name: kubernetes
  namespace: netbird
spec:
  name: kubernetes
  networkID: d6l9ef2fadhs73ak68a0
  address: kubernetes.default
  groups:
    - admins
