---
apiVersion: netbird.io/v1
kind: NBPolicy
metadata:
  name: admins-to-kube-api-1
  namespace: netbird
spec:
  name: Admins to Kube API 1
  sourceGroups:
    - admins
  destinationResource:
    name: kubernetes-1
  bidirectional: false
  protocols:
    - tcp
  ports:
    - 6443
