---
apiVersion: netbird.io/v1
kind: NBPolicy
metadata:
  name: admins-to-kubernetes
spec:
  name: Admins to Kubernetes
  sourceGroups:
    - admins
  destinationGroups:
    - dmn-fsn-tools
  bidirectional: false
  protocols:
    - tcp
