---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: mosquitto-configmap
    namespace: home-automation
    files:
      - config/mosquitto.conf
generatorOptions:
  disableNameSuffixHash: true
