---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.14.4
  interval: 30m
  values:
    prometheus:
      serviceMonitor:
        enabled: true

    l7Proxy: true
    loadBalancer:
      algorithm: maglev
      mode: dsr

    ingressController:
      enabled: false
      loadbalancerMode: shared

    hubble:
      serviceMonitor:
        enabled: true

    relay:
      prometheus:
        serviceMonitor:
          enabled: true

    k8sServiceHost: 192.168.2.141
    k8sServicePort: 7445

    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

    localRedirectPolicy: true
    rollOutCiliumPods: true
    
    bgp:
      enabled: false
      announce:
        loadbalancerIP: true
        podCIDR: false

    bgpControlPlane:
      enabled: true

    cluster:
      name: home
      id: 1

    ipam:
      mode: "kubernetes"
    ipv4NativeRoutingCIDR: 10.244.0.0/16

    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE

    tunnel: disabled

    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
