---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.14.4
  interval: 30m
  values:
    hubble:
      enabled: true
      serviceMonitor:
        enabled: true

      relay:
        prometheus:
          serviceMonitor:
            enabled: true

    prometheus:
      serviceMonitor:
        enabled: true

    operator:
      rollOutPods: true
      prometheus:
        serviceMonitor:
          enabled: true

    cluster:
      name: home
      id: 1

    cni:
      exclusive: false

    k8sServiceHost: localhost
    k8sServicePort: 7445

    rollOutCiliumPods: true
    localRedirectPolicy: true

    kubeProxyReplacement: true
    loadBalancer:
      algorithm: maglev
      mode: dsr

    bandwidthManager:
      enabled: true
      bbr: true
    bpf:
      masquerade: true
      tproxy: true

    l7Proxy: true

    enableCnpStatusUpdates: true
    endpointStatus:
      enabled: true
      status: "policy"

    ipam:
      mode: "kubernetes"

    ingressController:
      enabled: false
      loadbalancerMode: shared

    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    tunnel: "disabled"
    containerRuntime:
      integration: containerd

      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http

      relay:
        enabled: true
        rollOutPods: true

    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE

    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
