---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-app
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 10m
  path: "./kubernetes/home/apps/kube-system/cilium/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-config
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 10m
  path: "./kubernetes/home/apps/kube-system/cilium/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: cilium-app
