---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongo-operator
  namespace: database
spec:
  dependsOn:
    - name: mongo-operator-crds
  chart:
    spec:
      chart: community-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mongodb
      version: 0.7.9
  values:
    community-operator-crds:
      enabled: false
  interval: 1m0s
