---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - priority-class-critical.yaml
  - priority-class-high.yaml
  - priority-class-medium.yaml
  - priority-class-low.yaml
