---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 10m
  path: "./kubernetes/home/apps/monitoring/grafana/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: cloudnative-pg
