---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-tunnel-credentials.sops.yaml
  - secret-tunnel-certificates.sops.yaml
  - ../../base/cloudflared
patchesStrategicMerge:
  - values.yaml
