apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
    namespace: 1password
data:
    1password-credentials.json: ENC[AES256_GCM,data:/UMFgs1I1UAiBd7+1VnQ1RU5NQtr/g1fJdxHRhghWIuPT8L6DxFH/kFdp7tQVNL/5pW5TKe1ZECyZMFtC4O//1K2WmHDb/18mDQiEuSWfdL7eEskB1kdaWCv/j3AnDprwyK3/zxtk9IpaGrYWWbCcOfgD6mbR7aj/xug1fcE8VEaqinpPogVvsVK20AlrhChqyfSw489t+bDrzz9FQ+3xSGGiz4BXEPPxxgBPxTRFaXn6nAFu4T0QD9UvoEIdmvSi78pX+e641xZjSaoNYpqLrZyld+ZdRBe8TvTUkhcpq3lggFqFpb2WURma+Te/MDFtwaRCU97EOiQo1mfWstLn8GlFAh7O1zouVuujooW9s8AWaSHkQq+q0CzrbAb2paV1KY+3ArSTa/1xbV6RlrFbmzeCkbd17VC0OJmURgq07k6FYA9YtoXG6pZP04JvNQmPHaFRDQzDpBU8ver5PWmLwoPw70fWuBVmIFOLzsQfgf2lVyVXmDn32080PB4PQYcfzV+bsu9ix00UiZYzUAR2C30TDJ1ZnCnUC9UQYRPZlLZazRHJ1wsKbg4zuHOF5r5kqb90chrFYgDeV1t1/SGEPDVjZBo1vjT+uEm2zGzRXBVlpKGX+QJLwHD6yfLcRcXOh760agwwE6qZ2xRhsLi98cUOu2kE30Y48fLuMe0Dj+HKkw6Vw+6s8EzyoFydvk/oq4V908J4w1iPunLVkqKPczluJazEqtvMwX+H5xyTeLgaco6geXJyATQy5Isv1RNDw5fgbz7h/w1SPh/gdMcCgdDmaQUYRHB2mc4nknx4kThJ3pWwgNuFPw8vA+9LH14EC7eeF17xyr5eHNFCIPvZVIaEiql8DDEg27okAWMWxUeStf8stXHfhhd7QUDX/sAllV/Nk2L1/F8LhEDTK94OjVRFvDe/Bmd7HmLqMeSIFts1gJJdzFKeIIqAmCxBWwAIFDdyZJQUtnLYBQ+t1fstb6uzGadhMFtBVAXi+49zjJukasqHbXB4akhoZLBEk0OtfKBKBdkyplUOX0t+2Q6Ir109L5HzHl3Vk1ZF0mEnUnCCxKk+2q+OtaXdZLqfxpniqell9VjYpX0R+HOOai/e2y86X4/Ja2ONTft5IlYanuxEkh4zHXJjKFkmwvRLNQchxQjfH4FTnHQnZYyUtbLcD9ASYuOi4hPLvJGqvKi/Ay3KitjIYub8z0D12zkXZAqqhQlLmXo/REyVIVeQEuR4QeF2ti8GNOt+yE4E6Zmzm9XxzhQy2tfnC8nRiEDtlAhEgwYRqO7NgjDsc8ZOSBGNsv6HFG9RgChf8XvVMz/t0onH2Hpq02WYHpuPE7DNkk87ik4wlSqat0yQN8crZV+/XXsgAJdAdQg6ue3eUQo6kB8YHCFgDhc/YKdYnehCT+28LN/KKzv1YUqzLiS+Xs2Ja/k1Vhhgt5+0B0l36dbSiA1gM2IOqzPbySxV7dIZEzQ7jchzRO/qnfaE+5YK5VyqpA/8Zooa4zVX0bCpOqJW/ewK7r51UQx7wtB3ruWFfAs8GxcfkWE7vt2nLqTHJ/vfxU8hHqCKFmOVo+yP8wYdIFsYj8jLO3N7ZCbUt+XN24pzl1CmxUnR5ctLC0a/QTYSXRo9UhhhzRhbuR/o1fTPkmSxi6o0guJmNMk9vk+Jj7ImrvDIKk/Lt8N9i37LKqze4B/oGigNH4L3diO0dKOmsuJSp+uZLZ+AGUXncQ0aNG+lMHLAqF+cdrjKznZNn03HyW1GZw6Zh6tPVnJDGPaZ/MNqL0mAX+1xf8yGD1fkzyxeXUXnDzzTGnlSIasvObS6RHDY0VklR7SpuiXMhnHuA/To4EBaxGO1otna2jHBR0fRDf8DNPDFxjvvUNKXyaDUINJbM6H4uDELIExwhGtapkM+tJygRv14uxuycrw2c1rcP8/yjnr/SByiwoOoSfBkDWVmG5cFjn/EA7tfxFCEjO9FAe4n1WaDsogO1s44I4H8cH2Nd9/qAiitRm8xwW+m9jWdssEe2MlyVL1i/Ca1DLjp1WPDDWGZjSqHbgwODlw5Zq1cITiDhaTrRp0qMRouVezJB1acsrjB8hZmnqfj8eS2aYuQa9DziRdrQPV4ghHruGuWaXPRFylahEyzanCOeWo6Tvq/Wz3OFXU8mxLD/ZAYA+PTaCWeLOu9Y1xaOEswIKhe/eqdSxRGlVqXMSMzVB1PfEBPliO0Wf5H/mQbF8nNb1m0s7tpsy5Er672AcTfJMm6DmYpCsXnba3QE256+fHFsPSHyZ8ebk8Td1HlwTazp0lfR26RVsdlSb/gSvZBu5x9ZZvVe8c8b3clREfsA6lB7mTObGyMpVo64HS/FopJ3q9vxWoXcHTBEKddz848utY5Zxw1Q9d517CxiACiz0G1A7TlhoGO3gKPK6f5cpWaoeTtXBDgUeUYOR3o0a2IuZDkPCn+xf+gj5DG94NFLBJSzxs+JdNuFisuVoQoUF1+Sit6gB1pxCWntAJ7rIFh6GXbmVbdtGV/7kPKDoCrMkldWHT4qzuQ1Wya0doEw8u4nEOEQxSX92ViBU=,iv:P0/NgM3L2vVwj41O/+OmUBHXa9TKBj0FFstObTahQxE=,tag:QDhXW29Sj1+jC5fK1YmRHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-03T19:51:53Z"
    mac: ENC[AES256_GCM,data:+aM7E+r99J+Lf696QOdN7ddtUs/Qp81UQbKhqY97kXQ0cGg+LDsFbcgfyoN9l23aNpj3igmkgELLO4rP2YjOuBBMwOGOk8kWn5lCvCuG13MpaSANL7dsgVqfzk7/YuoznY95RNdiOjdpKhIb9IfvfVcfQCr4h0AbfAAvkq+MPng=,iv:31r5ZJHlEnpXUKk/W0aY0vpum/c/4Mamae+7kSlbfcU=,tag:rX6+22E0O6X4onvPCxEoCQ==,type:str]
    pgp:
        - created_at: "2023-04-03T19:51:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxfu3g8LdXaRAQ/+N4/F1L462TdOsGBBenTB1P1jUhW3JZhqg3cg7Y38xlxQ
            aaWpLKlM8clPLmdezTniwHKUH8J5rBY3K5Y+rQXI4n3+L2LHnkRIolMD85kI5ziN
            53ZSID3E51HaQXrdj30KW6d/F5A2piy/8JGC9Wt+hKaeaXCKDc6xXDnGYZrjscn4
            mgqKOrxRb0mDI31WHAGN6tS0m9RIMItbY5EG9cFhWO9AivGeqQhVclM+UhgOVEKe
            9iqbKfRrZIEhxSVvof4FXrGytHidPThtedNzAWwLJhQojacTxgZPwS/t5jQC9SYY
            lE4ovHDu6U7TGqaSsmvf2eWVrmTO2ReYBHZYWVhlMVO6m621EhPOiuCVYKcRsTTH
            cFEMOemzE5W9W177J0t25RO3WsbI0xXlt1ixk1H+W4qZQSI1v08Nhsi2dgq78Ay3
            jlZ+bkOYQxWIdiNLDQoAxD/pkTWOeF/8c6rdxucYrt7H2q95Okx+djhCKrYauk6y
            DbSKRX8ZU9QLKg7cqlNWBjntio32CNyW2N753gYzatkSP25uC8d7t+Mh8S44WEu5
            8DpcZpJqkALTHnIIbv+t/V6HKeHHLfNH/WFyAAoTvAToYitF9JV3eMWmH8LWCxmF
            thoJCnavkq6825vHmk+wve+ifjORN7+mYrDxa+G2rVJ8YMuok1ClSvKx73MTBuXS
            XgGJnxR4CChJeFYOHTsz3iB7YGjJ56bOEMU28KyedgaHgpEZnbYxLfMSxRW+c0a2
            KFVVAW1hNyFXmDcS0Q382amU0HYBusSBzY3NqQoLfL4dcdEcyjviFZTAiPZi9ZE=
            =Ap1Y
            -----END PGP MESSAGE-----
          fp: 8BC21F9620077AD4B9BD97EF5C350D68F61028B3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
