---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: cloudflare
spec:
  interval: 12h
  approvePlan: "auto"
  path: "./infrastructure/terraform/cloudflare"
  sourceRef:
    kind: GitRepository
    name: flux-system
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tfe-cli-config
  varsFrom:
    - kind: Secret
      name: cloudflare-token
