---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: cloudflare
spec:
  interval: 12h
  approvePlan: "auto"
  path: "./infrastructure/terraform/cloudflare"
  sourceRef:
    kind: GitRepository
    name: flux-system
  runnerPodTemplate:
    spec:
      env:
        - name: TF_VAR_cloudflare_token
          valueFrom:
            secretKeyRef:
              name: cloudflare-token
              key: token
