---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: tfe-cli-config
  namespace: develop
spec:
  itemPath: "vaults/Kubernetes/items/tfe-cli-config"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-token
  namespace: develop
spec:
  itemPath: "vaults/Kubernetes/items/cloudflare-token"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: truenas-token
  namespace: develop
spec:
  itemPath: "vaults/Kubernetes/items/truenas-token"
