---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  targetNamespace: home-automation
  interval: 10m
  path: "./kubernetes/home/apps/home-automation/home-assistant/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: cloudnative-pg
