---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate
  namespace: flux-system
spec:
  targetNamespace: develop
  interval: 10m
  path: "./kubernetes/home/apps/develop/renovate/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: connect
      namespace: 1password
