---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  targetNamespace: download
  interval: 10m
  path: "./kubernetes/home/apps/download/qbittorrent/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbtools
  namespace: flux-system
spec:
  targetNamespace: download
  interval: 10m
  path: "./kubernetes/home/apps/download/qbittorrent/tools"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  dependsOn:
    - name: qbittorrent
