apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    replicaCount: 3
    serviceMonitor:
      enabled: true
    secret:
      certificates:
        name: tunnel-credentials
    annotations:
      operator.1password.io/item-path: "vaults/Kubernetes/items/cloudflared-credentials"
      operator.1password.io/item-name: "tunnel-credentials"
    config:
      tunnel: 6268786c-0c8f-424c-a86b-dc088293a5b4
      credentials-file: /etc/cloudflared/creds/6268786c-0c8f-424c-a86b-dc088293a5b4.json
