---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: develop
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: actions-runner-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
      version: 0.23.5
  values:
    authSecret:
      create: true
  interval: 1m0s
