---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovate
  namespace: develop
spec:
  chart:
    spec:
      chart: renovate
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: renovate
      version: 37.43.4
  values:
    cronjob:
       schedule: "@hourly"
    renovate:
      config: '{}'
    dind:
      enabled: true
    image:
      repository: "ghcr.io/renovatebot/renovate"
  interval: 1m0s
