---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovate
  namespace: develop
spec:
  chart:
    spec:
      chart: renovate
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: renovate
      version: 35.57.0
  values:
    cronjob:
       schedule: "@hourly"
    renovate:
      config: '{}'
    dind:
      enabled: true
  interval: 1m0s
