---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/1password.yaml
  - ../base/cert-manager.yaml
  - ../base/cloudflare.yaml
  - ../base/database.yaml
  - ../base/develop.yaml
  - ../base/monitoring.yaml
  - ../base/shared.yaml
  - ../base/openebs-jiva.yaml
  - ../base/network.yaml
patchesStrategicMerge:
  - develop.yaml
  - monitoring.yaml
  - openebs-jiva.yaml
