---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: download
spec:
  dependsOn:
    - name: openebs-mayastor
      namespace: storage
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        openebs.io/engine: mayastor
    controllers:
      main:
        pod:
          annotations:
            operator.1password.io/item-path: "vaults/Kubernetes/items/sonarr-secret"
            operator.1password.io/item-name: "sonarr-secret"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.2.1341@sha256:e7e1a75fa1586559f91d5e26caac72f96f1e18ae01ccb2d7c7ce589a3bedaca4
            env:
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__PORT: 8989
              SONARR__AUTHENTICATION_METHOD: External
              SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              SONARR__APPLICATION_URL: "http://sonarr.home.damoun.cloud"
              SONARR__LOG_LEVEL: info
              SONARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sonarr-secret
                    key: api_key
            resources:
              requests:
                cpu: 20m
                memory: 512M
              limits:
                memory: 768M
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: "sonarr.home.damoun.cloud"
            paths:
              - path: /
                service:
                  name: main
                  port: http
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: openebs-mayastor-dual-replica
      tvshow:
        enabled: true
        type: nfs
        server: nas.home.damoun.cloud
        path: /mnt/pool1/video/tv-show
        globalMounts:
          - path: /data/tv-show
