---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: ns
    - name: repo
    - name: crds
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/cluster-1
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
