---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: repo
  namespace: flux-system
spec:
  dependsOn:
    - name: ns
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./repo/cluster-1
  prune: true
  wait: true
